<!-- <select onchange="print_city('shadow-sm form-select city', this.selectedIndex);" id="state" class="shadow-sm form-select state" style="font-family:Roboto, sans-serif;" name="state" required> -->
<!-- <select onchange="print_city('city', this.selectedIndex);" id="state" name="pstate" class="form-control" required> -->
<option value="">Select State</option>
<option value="Andaman &amp; Nicobar">Andaman &amp; Nicobar</option>
<option value="Andhra Pradesh">Andhra Pradesh</option>
<option value="Arunanchal Pradesh">Arunanchal Pradesh</option>
<option value="Assam">Assam</option>
<option value="Bihar">Bihar</option>
<option value="Chandigarh">Chandigarh</option>
<option value="Chhattisgarh">Chhattisgarh</option>
<option value="Dadra Nagar &amp; Haveli">Dadra Nagar &amp; Haveli</option>
<option value="Daman &amp; Diu">Daman &amp; Diu</option>
<option value="Delhi">Delhi</option>
<option value="Goa">Goa</option>
<option value="Gujarat">Gujarat</option>
<option value="Haryana">Haryana</option>
<option value="Himachal Pradesh">Himachal Pradesh</option>
<option value="Jammu &amp; Kashmir">Jammu &amp; Kashmir</option>
<option value="Jharkhand">Jharkhand</option>
<option value="Karnataka">Karnataka</option>
<option value="Kerala">Kerela</option>
<option value="Lakshadweep">Lakshadweep</option>
<option value="Madhya Pradesh">Madhya Pradesh</option>
<option value="Maharashtra">Maharashtra</option>
<option value="Manipur">Manipur</option>
<option value="Meghalaya">Meghalaya</option>
<option value="Mizoram">Mizoram</option>
<option value="Nagaland">Nagaland</option>
<option value="Odisha">Odisha</option>
<option value="Puducherry">Puducherry</option>
<option value="Punjab">Punjab</option>
<option value="Rajasthan">Rajasthan</option>
<option value="Sikkim">Sikkim</option>
<option value="Tamil Nadu">Tamil Nadu</option>
<option value="Tripura">Tripura</option>
<option value="Telangana">Telangana</option>
<option value="Uttar Pradesh">Uttar Pradesh</option>
<option value="Uttarakhand">Uttarakhand</option>
<option value="West Bengal">West Bengal</option>
<!-- </select> -->